### ISSUE TITLE
As a user i want to have a possibility to print remaining chanda

### ISSUE THREAD

**Issue by capono** [iNeedCode/Maalify#90]
For me, it is difficult to check each budget and copy the list sort it and then print it. Better would be to have a sorted list with all the rest payment of each payer. Also it would be good to have a feature which tells which payors have to most rest payments left for each month to have summary of people which should be contacted, like for example a  person which has not paid Chanda for 3 Months, where the Mail should go maybe more often or the email format should be more highlighted. Also, a notification/alert for the systemuser to check on these people would be great.

**Comment by iNeedCode** [comment]
@capono Thx for your input. 

I've created new issues or tasks that tackles your request, if you wanna contribute feel free contact me.

https://github.com/iNeedCode/Maalify/issues/92
https://github.com/iNeedCode/Maalify/issues/93
